services:
  - type: web
    name: mdl-business
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: root
      - key: DB_NAME
        value: ecommerce
      - key: DB_PORT
        value: 3306
      - key: STRIPE_PUBLIC_KEY
        value: ""
      - key: STRIPE_SECRET_KEY
        value: ""
      - key: TWILIO_ACCOUNT_SID
        value: ""
      - key: TWILIO_AUTH_TOKEN
        value: ""
      - key: ADMIN_WHATSAPP
        value: ""