"""Ajout des tables commandes et lignes_commandes

Revision ID: 2621b8b40810
Revises: 2ba98adfc3a8
Create Date: 2026-09-03 14:56:49.852511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2621b8b40810'
down_revision = '2ba98adfc3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse_livraison', sa.Text(), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=False),
    sa.Column('pays', sa.String(length=50), nullable=False),
    sa.Column('sous_total', sa.Float(), nullable=False),
    sa.Column('frais_livraison', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('lignes_commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('nom_produit', sa.String(length=100), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lignes_commandes')
    op.drop_table('commandes')
    # ### end Alembic commands ###
