"""Initial migration

Revision ID: 2ba98adfc3a8
Revises: 
Create Date: 2026-09-03 13:34:44.725689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba98adfc3a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('est_active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=True),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('est_admin', sa.Boolean(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('date_derniere_connexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('prix_promo', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('est_disponible', sa.Boolean(), nullable=True),
    sa.Column('image_principale', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produits')
    op.drop_table('utilisateurs')
    op.drop_table('categories')
    # ### end Alembic commands ###
