"""Ajout des champs pour les services

Revision ID: f904f939bbe8
Revises: 0b8ec0b822e5
Create Date: 2026-09-04 00:04:04.944057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f904f939bbe8'
down_revision = '0b8ec0b822e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_service', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duree', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('livrable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('garantie', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('caracteristiques', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_column('caracteristiques')
        batch_op.drop_column('garantie')
        batch_op.drop_column('livrable')
        batch_op.drop_column('duree')
        batch_op.drop_column('est_service')

    # ### end Alembic commands ###
